"""Platform protocol — splits methods only where the platform API actually differs.

For Threads/X/Mastodon/Bluesky (v1), `delete(media_id)` is one endpoint, exposed
as a single method here. `publish_post` and `publish_reply` ARE separate
because the underlying API needs a `reply_to_id` for replies. Add new platforms
by implementing this protocol.
"""
from __future__ import annotations

from typing import Any, Protocol, runtime_checkable


@runtime_checkable
class Platform(Protocol):
    name: str

    def authorize_url(self, state: str, scopes: list[str]) -> str: ...
    def exchange_code(self, code: str) -> dict[str, Any]: ...   # {access_token, expires_at, ...}
    def refresh_token(self) -> dict[str, Any]: ...
    def publish_post(self, *, text: str, image_url: str | None = None) -> dict[str, Any]: ...
    def publish_reply(self, *, parent_id: str, text: str, image_url: str | None = None) -> dict[str, Any]: ...
    def delete(self, media_id: str) -> bool: ...
    def user_insights(self, *, days: int = 2) -> dict[str, Any]: ...
    def normalize_webhook(self, raw: dict) -> list[dict]: ...
    def parse_account(self, me_payload: dict) -> dict[str, Any]: ...